### ISSUE TITLE
Cloudformation Template Issue

### ISSUE THREAD

**Issue by swappyp20** [aws-quickstart/connect-integration-teleopti-wfm#15]
Hi Team,

We are using "**_connect-integration-teleopti-wfm_**" quickstart for one of our deployment.
While deploying the cloud formation template in london region, we found that there are lot of issues related to resource creation.

we have manually created a S3 bucket as per the path referenced in the template & added lambda.zip file to the folder.

The lambda deployment package has a lot of issues which throws an error while running cloud formation template.
See the attached screenshot of the cloud-formation evenets output: a lot of events are still in "**_CREATE_IN_PROGRESS"_** mode.

![image](https://user-images.githubusercontent.com/4953496/75772890-d0441880-5d72-11ea-8b75-135c480cf6c1.png)
![image](https://user-images.githubusercontent.com/4953496/75772905-d639f980-5d72-11ea-86a6-691220bb4815.png)

we got stuck at it & we don't know how to proceed further. Can someone help us to resolve the issue. @jayyeras @KristaCrout @sshvans 

Regards,
Swapnil Pawar

**Comment by vsnyc** [comment]
@KristaCrout - could you validate that the templates are working properly for you? I had a working session with Swapnil earlier today and ran into an issue that the live templates had an incorrect in the inline python lambda function due to version change from 2.7 to 3.7. I've fixed that in commit https://github.com/aws-quickstart/connect-integration-teleopti-wfm/commit/98f2c8259b4981b3427ab993e3135af5035410dd, but I don't have Teleopti credentials to test it end-to-end.

**Comment by KristaCrout** [comment]
I can test it tonight to confirm one way or the other.

Respectfully,
Krista Crout

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by swappyp20** [comment]
Hi Krista,

Any update on testing part? 

Regards,
Swapnil Pawar

**Comment by swappyp20** [comment]
Hi @vsnyc,

yesterday we deployed the cloudformation template & we got the Error: 

ERROR	(node:8) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

In the main.js, we need to look at the code level & change it to new method so that it will throw any error in future becasue you might be knowing that the node 8.x is out of lambda and now only node 10.x and 12.x  versions are supported.

Looking forward to hearing from you.

Thanks,
Swapnil Pawar

**Comment by vsnyc** [comment]
@KristaCrout - could you provide an update with the result of your testing. I don't have the credentials to test this. I'd like to arrange a meeting to resolve this, please send me an email at shukvino@amazon.com

**Comment by vsnyc** [comment]
This has been fixed in PR https://github.com/aws-quickstart/connect-integration-teleopti-wfm/pull/17
