### ISSUE TITLE
TeleoptiIntegrationFunction: cannot promisify an API that has normal methods with 'Async'-suffix 

### ISSUE THREAD

**Issue by vsnyc** [aws-quickstart/connect-integration-teleopti-wfm#19]
Receiving the following error when TeleoptiIntegrationFunction is executed.

""TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix"," related to the bluebird.

Here is the documentation related to the error. http://bluebirdjs.com/docs/error-explanations.html

**Comment by vsnyc** [comment]
@swappyp20 - Take a look at the PR #20 which fixes this issue, and has several other minor fixes.

**Comment by swappyp20** [comment]
> @swappyp20 - Take a look at the PR #20 which fixes this issue, and has several other minor fixes.

Sure Vinod. We also did some modification at code level yesterday and it was working. We will take a pull request and update it at our end. Thank you.
